### ISSUE TITLE
Limit kubectl commands

### ISSUE THREAD

**Issue by IngussNeilands** [infracloudio/botkube#183]
I would like to suggest adding option to limit specific kubectl commands.

For example - I would like to disable `describe secret` command, because it could reveal some sensitive data.

**Comment by PrasadG193** [comment]
@IngussNeilands we can restrict BotKube to access only specific resources by adding rules to in `Clusterrole` which is used by `botkube-sa` service account
https://github.com/infracloudio/botkube/blob/develop/helm/botkube/templates/clusterrole.yaml

**Comment by PrasadG193** [comment]
We are also adding a support to restrict command execution from a configured channel only https://github.com/infracloudio/botkube/issues/235

**Comment by cookandy** [comment]
Would it also be possible to restrict who can run `kubectl` commands by slack username?

**Comment by fliphess** [comment]
Using @botkube get secret <someverysecretsecret> -o yaml will result in a dataleak, I'd love to use `get pods` and `get ns` etc, but prefer to keep my passwords out of slack :)

**Comment by girishg4t** [comment]
@PrasadG193 i can take a look on this

**Comment by PrasadG193** [comment]
@girishg4t let's finalize the BotKube configuration format before you start

**Comment by PrasadG193** [comment]
The straight forward way would be to add one more section in settings.kubectl section in resource configuration. Something like:
```
settings:
  kubectl:
    # Set true to enable kubectl commands execution
    enabled: true
    # List of allowed commands
    commands:
      # method which are allowed
      verbs: ["get", "logs"]
      # resource configuration which is allowed
      resources: ["deployments", "pods"]
```
