### ISSUE TITLE
Make update events configurable to watch only specific fields

### ISSUE THREAD

**Issue by PrasadG193** [infracloudio/botkube#203]
**Is your feature request related to a problem? Please describe.**
Currently, BotKube watches and sends notifications only about updates in `spec` of a resource when configured to watch `update` events
It should be configurable which resource fields we want watch and get notifications for when updated

**Describe the solution you'd like**
We can change `update` fields in configuration to -
```
update:
  fields:
    - spec
    - metadata
    - status
  includeDiff: true
```
