### ISSUE TITLE
Pass BotKube communication settings as a K8s Secret

### ISSUE THREAD

**Issue by PrasadG193** [infracloudio/botkube#211]
**Is your feature request related to a problem? Please describe.**
BotKube config contains sensitive info like Tokens which is passed to backend via ConfigMap. We should pass the communication setting as a K8s Secret. Also, restrict BotKube to access Secret resources using `@BotKube` commands by default

**Comment by slalwani97** [comment]
Would like to check my approach first before implementing: 
1. Move communication settings to secret.
```
apiVersion: v1
kind: Secret
metadata:
  name: botkube-secret
type: Opaque
stringData:
  communication.yaml: |
    # Communication settings
    communications:
      # Settings for Slack
      slack:
        enabled: false
        channel: 'SLACK_CHANNEL'
        token: 'SLACK_API_TOKEN'
        notiftype: short                            # Change notification type short/long you want to receive. notiftype is optional and Default notification type is short (if not specified)

      # Settings for Mattermost
      mattermost:
        enabled: false
        url: 'MATTERMOST_SERVER_URL'                # URL where Mattermost is running. e.g https://example.com:9243
        token: 'MATTERMOST_TOKEN'                   # Personal Access token generated by BotKube user
        team: 'MATTERMOST_TEAM'                     # Mattermost Team to configure with BotKube
        channel: 'MATTERMOST_CHANNEL'               # Mattermost Channel for receiving BotKube alerts
        notiftype: short                            # Change notification type short/long you want to receive. notiftype is optional and Default notification type is short (if not specified)

      # Settings for ELS
      elasticsearch:
        enable: false
        server: 'ELASTICSEARCH_ADDRESS'              # e.g https://example.com:9243
        username: 'ELASTICSEARCH_USERNAME'
        password: 'ELASTICSEARCH_PASSWORD'
        # ELS index settings
        index:
          name: botkube
          type: botkube-event
          shards: 1
          replicas: 0

      # Settings for Webhook
      webhook:
        enabled: false
        url: 'WEBHOOK_URL'                          # e.g https://example.com:80
```
2. This will be mounted as a seperate file so this file should be read and unmarshal into config structure.
```
// New returns new Config
func New() (*Config, error) {
	c := &Config{}
	configPath := os.Getenv("CONFIG_PATH")
	configFilePath := filepath.Join(configPath, ConfigFileName)
	communicationFilePath := filepath.Join(configPath, communicationFileName)
	configFile, err := os.Open(configFilePath)
	defer configFile.Close()
	if err != nil {
		return c, err
	}

	b, err := ioutil.ReadAll(configFile)
	if err != nil {
		return c, err
	}

	if len(b) != 0 {
		yaml.Unmarshal(b, c)
	}

	communicationFile, err = os.Open(communicationFilePath)
	defer communicationFile.Close()
	if err != nil {
		return c, err
	}

	b, err = ioutil.ReadAll(file)
	if err != nil {
		return c, err
	}

	if len(b) != 0 {
		yaml.Unmarshal(b, c)
	}
	return c, nil
}
```
Is this the correct approach?
