### ISSUE TITLE
[BUG] Error Posting Webhook: Ɛ

### ISSUE THREAD

**Issue by Timvissers** [infracloudio/botkube#252]
**Describe the bug**
When sending job events to (slack) webhook, the following occurs.
We are using v0.9.1 on AKS 1.16.
I tested this with different webhooks. The webhooks work for other purposes, eg when using the same webhook config in kubewatch, it works.

ERRO[2020-04-09T04:19:50Z] Error Posting Webhook: Ɛ
DEBU[2020-04-09T04:19:50Z] Event Not Sent to Webhook { Job Created Job 334a411a-eaff-431d-b73b-b1c1e1c244c0 icobrain-jobs [] create   info not-configured  2020-04-09 04:19:49 +0000 UTC 0  false [] []}
DEBU[2020-04-09T04:19:50Z] Event successfully sent to Webhook { Job Created Job 334a411a-eaff-431d-b73b-b1c1e1c244c0 icobrain-jobs [] create   info not-configured  2020-04-09 04:19:49 +0000 UTC 0  false [] []}

**To Reproduce**
Configuration:
```
logLevel: debug
config:
  resources:
    - name: job
      namespaces:
        include:
          - all
        ignore:
          -
      events:
        - create
        - update
  communications:
    webhook:
      enabled: true
      url: https://hooks.slack.com/services/<redacted>
  settings:
    upgradeNotifier: false
```

Start a job

**Expected behavior**
The job should be posted to the webhook without error
