### ISSUE TITLE
Delete PVC not sending event to webhook 

### ISSUE THREAD

**Issue by prasenforu** [infracloudio/botkube#276]
When I am deleting PVC in namespace its throwing PV resource instead of PVC. seems its a BUG

My configuration as follows..

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: botkube-configmap
  namespace: velero-auto
  labels:
    app: botkube
data:
  resource_config.yaml: |
    ## Resources you want to watch
    resources:
      - name: service
        namespaces:
          include:
            - all
          ignore:
            -
        events:
          - delete
      - name: ingress
        namespaces:
          include:
            - all
          ignore:
            -
        events:
          - delete
      - name: namespace
        namespaces:
          include:
            - all
          ignore:
            -
        events:
          - delete
      - name: persistentvolume
        namespaces:
          include:
            - all
          ignore:
            -
        events:
          - delete
      - name: persistentvolumeclaim
        namespaces:
          include:
            - all
          ignore:
            -
        events:
          - delete
      - name: role
        namespaces:
          include:
            - all
          ignore:
            -
        events:
          - delete
      - name: rolebinding
        namespaces:
          include:
            - all
          ignore:
            -
        events:
          - delete
      - name: clusterrole
        namespaces:
          include:
            - all
          ignore:
            -
        events:
          - delete
      - name: clusterrolebinding
        namespaces:
          include:
            - all
          ignore:
            -
        events:
          - delete
      - name: configmap
        namespaces:
          include:
            - demo-mongo
          ignore:
            -
        events:
          - delete
    # Check true if you want to receive recommendations
    # about the best practices for the created resource
    recommendations: true
    # Setting to support multiple clusters
    settings:
      # Cluster name to differentiate incoming messages
      clustername: not-configured
      # Kubectl executor configs
      kubectl:
        # Set true to enable kubectl commands execution
        enabled: false
        # set Namespace to execute botkube kubectl commands by default
        defaultNamespace: default
        # Set true to enable commands execution from configured channel only
        restrictAccess: false
      # Set true to enable config watcher
      configwatcher: true
      # Set false to disable upgrade notification
      upgradeNotifier: true
```
