### ISSUE TITLE
[BUG] Helm Chart clusterrole invalid if PSP and rbac are both enabled

### ISSUE THREAD

**Issue by mitchellmaler** [infracloudio/botkube#325]
**Describe the bug**
If both RBAC and PSP are enabled the two rules added to the clusterrole are not indented the same.
https://github.com/infracloudio/botkube/blob/develop/helm/botkube/templates/clusterrole.yaml#L11

**To Reproduce**
Install chart (or template) with both rbac and psp enabled.

**Expected behavior**
Cluster role is set correctly.

**Screenshots**

```yaml
---
# Source: botkube/templates/clusterrole.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: botkube-clusterrole
  labels:
    app.kubernetes.io/name: botkube
    helm.sh/chart: botkube-v0.10.0
    app.kubernetes.io/instance: botkube
    app.kubernetes.io/managed-by: Helm
rules:
    - apiGroups:
      - '*'
      resources:
      - '*'
      verbs:
      - get
      - watch
      - list
  - apiGroups: ["extensions"]
    resourceNames: ["botkube-psp"]
    resources: ["podsecuritypolicies"]
    verbs: ["use"]

```

**Additional context**
