### ISSUE TITLE
[BUG] BotKube is crashing when invalid resource format provided

### ISSUE THREAD

**Issue by PrasadG193** [infracloudio/botkube#333]
**Describe the bug**

BotKube with latest build crashes in name in resource config is not in `G/V/R` format

**To Reproduce**
Deploy BotKube from develop branch with the latest image. Use the following resource configuration
```
config:
  ## Resources you want to watch
  resources:
    - name: pod
      namespaces:
        include:
          - all
        ignore:
          -    
```

**Additional Context**
Crash logs: https://gist.github.com/PrasadG193/4da70950d10e5a75815d9bfde586e4a2
