### ISSUE TITLE
[BUG] No response to certain Slack messages and it always requires --cluster-name

### ISSUE THREAD

**Issue by othyn** [infracloudio/botkube#408]
**Describe the bug**
Having some strange behaviour with the commands via Slack. I have just installed this into my cluster using the `v1.11.0` script, following the installation steps.

The installation works fine and its on the whole, an excellent tool. Amazing work by the team here!

The problem arises when I try to use commands via Slack. Some of the commands work, some of them do nothing and do not respond with anything either.

The documentation specifies that running a command without the --cluster-name flag should run on all clusters, but nothing is returned as a response to Slack.

For example:

- `@BotKube ping`
    - This always works, with the response:

```
pong from cluster 'production.kammadata.k8s.local'

K8s Server Version: v1.18.9
BotKube version: v0.11.0
```

- `@BotKube get pods --cluster-name=production.domain.local`
    - This always works, but only when specifying the `--cluster-name`
- `@BotKube get pods`
    - This **never** works, with no response and nothing in the pod logs
- `@BotKube commands list`
    - This **never** works, with no response and nothing in the pod logs

Not sure what I'm doing wrong. I have the Slack config as follows:

```
stringData:
  comm_config.yaml: |
    # Communication settings
    communications:
      # Settings for Slack
      slack:
        enabled: true
        channel: '#kubernetes-sonar'
        token: '<redacted>'
        notiftype: short                            # Change notification type short/long you want to receive. notiftype is optional and Default notification type is short (if not specified)
```

The settings configured as follows:

```
# Setting to support multiple clusters
settings:
  # Cluster name to differentiate incoming messages
  clustername: production.domain.local
  # Kubectl executor configs
  kubectl:
    # Set true to enable kubectl commands execution
    enabled: true
    commands:
      # method which are allowed
      verbs: ["api-resources", "api-versions", "cluster-info", "describe", "diff", "explain", "get", "logs", "top", "auth"]
      # resource configuration which is allowed
      resources: ["deployments", "pods" , "namespaces", "daemonsets", "statefulsets", "storageclasses", "nodes"]
    # set Namespace to execute botkube kubectl commands by default
    defaultNamespace: default
    # Set true to enable commands execution from configured channel only
    restrictAccess: false
  # Set true to enable config watcher
  configwatcher: true
  # Set false to disable upgrade notification
  upgradeNotifier: true
```

I've tried:
- Changing the channel name
- Doing a complete re-installation from scratch of v1.11.0, deleting all the old infrastructure and trying again
- Putting the clustername in quotes in the settings
- Enabling and disabling the `restrictAccess` flag

Any help would be greatly appreciated!

**To Reproduce**
1. Install a fresh installation of v1.11.0
2. Go through the setup steps and configure Slack
3. Cannot run commands as intended

**Expected behavior**
For any and all commands, a response should be given. The `--cluster-name` flag is also optional in the documentation, but does not work in production.

**Screenshots**
<none>

**Additional context**
<none>
