### ISSUE TITLE
[BUG] Ignored namespace list gets ignored

### ISSUE THREAD

**Issue by bribroder** [infracloudio/botkube#419]
Since updating from 0.10.0 to 0.11.0, ignoring some namespaces while including "all" doesn't work--the ignore list seems to simply be ignored:

```
config:
  ## Resources you want to watch
  resources:
  - name: v1/pods
    namespaces:
      include:
        - all
      ignore:
        - test
    events:
      - all
    updateSetting:
      includeDiff: true
      fields:
        - spec.template.spec.containers[*].image
        - status.availableReplicas

  # Check true if you want to receive recommendations
  # about the best practices for the created resource
  recommendations: true

  # Cluster Setting to manage command execution access
  settings:
    # Set true to enable kubectl commands execution
    allowkubectl: false

    # Set true to enable commands execution from configured channel only
    restrictAccess: false

    # Set true to enable config watcher
    configwatcher: true

    # Set false to disable upgrade notification
    upgradeNotifier: true
```

Specifying certain namespaces to include does work, but isn't ideal
