### ISSUE TITLE
[BUG] prometheus servicemonitor selector mismatch with service labels

### ISSUE THREAD

**Issue by asurahack** [infracloudio/botkube#431]
**Describe the bug**
Current servicemonitor selector from botkube helm chart does not match with labels of created botkube kubernetes service:

[servicemonitor selector block](https://github.com/infracloudio/botkube/blob/develop/helm/botkube/templates/servicemonitor.yaml#L20-L27):
```
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "botkube.name" . }}
      helm.sh/chart: {{ include "botkube.chart" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      component: controller
      app: botkube
```
[service labels block](https://github.com/infracloudio/botkube/blob/develop/helm/botkube/templates/service.yaml#L6-L11):
```
  labels: 
    app.kubernetes.io/name: {{ include "botkube.name" . }}
    helm.sh/chart: {{ include "botkube.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}  
    app: botkube

```
As you see, extra label `component: controller` makes service unmatchable for servicemonitor

**To Reproduce**
1. install botkube chart v0.11.0 from https://infracloudio.github.io/charts with .Values.serviceMonitor.enabled: true
2. go to your prometheus/targets
3. see, that there are 0/0 up for botkube targets

**Expected behavior**
With correct servicemonitor selector there should be actual count of botkube pods
