### ISSUE TITLE
[BUG] Notifier not working with Microsoft Teams (Skipping SendMessage)

### ISSUE THREAD

**Issue by cerebrate** [infracloudio/botkube#507]
**Describe the bug**

I have BotKube installed on my cluster and am attempting to receive notifications from it using Microsoft Teams. Unfortunately, after a `notifier start`, no notifications are received for any events or cluster changes. Instead, the following events are recorded in the BotKube pod log:

```
INFO[2021-08-01T19:28:21Z] Skipping SendMessage since conversation ref not set
INFO[2021-08-01T19:28:39Z] Skipping SendMessage since conversation ref not set 
INFO[2021-08-01T19:28:40Z] Skipping SendMessage since conversation ref not set 
INFO[2021-08-01T19:28:40Z] Skipping SendMessage since conversation ref not set 
INFO[2021-08-01T19:28:41Z] Skipping SendMessage since conversation ref not set
INFO[2021-08-01T19:29:09Z] Skipping SendMessage since conversation ref not set
INFO[2021-08-01T19:29:20Z] Skipping SendMessage since conversation ref not set
INFO[2021-08-01T19:29:31Z] Skipping SendMessage since conversation ref not set
INFO[2021-08-01T19:30:00Z] Skipping SendMessage since conversation ref not set
INFO[2021-08-01T19:30:10Z] Skipping SendMessage since conversation ref not set
```

These only occur when the notifier is running. They cease on a `notifier stop` command and continue on a following `notifier start`.

In all other ways, communications with BotKube via Teams appear to be functioning properly. Commands (such as the aforementioned notifier start/stop commands), including kubectl commands, are received and executed, and their output displayed as normal.

(The logs also display the following periodic warning:

`W0801 19:30:56.180450       1 warnings.go:70] networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress`

but I don't think that is connected to this issue. But I mention it for the sake of full disclosure.)

**To Reproduce**

I have no specific reproduction steps to produce this behavior; this is simply what I saw on setting up the cluster in accordance with the instructions at https://www.botkube.io/installation/teams/ . My Helm configuration file read as follows:

```
logLevel: info

communications:
  teams:
    enabled: true
    appID: '[REDACTED]'
    appPassword: '[REDACTED]'
    notiftype: long

config:
  settings:
    clustername: harmony
    kubectl:
      enabled: true

ingress:
  create: false

nodeSelector:
  kubernetes.io/arch: amd64
```

The ingress was manually configured as follows, to permit Traefik to be configured to strip out a path element used to get inbound traffic from Teams through our reverse proxy server:

```
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-botkube
  namespace: infrastructure
spec:
  stripPrefix:
    prefixes:
      - /botkube
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: botkube
  namespace: infrastructure
  labels:
    app: botkube
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: 'websecure'
    traefik.ingress.kubernetes.io/router.tls: 'true'
    traefik.ingress.kubernetes.io/router.middlewares: 'infrastructure-strip-botkube@kubernetescrd'
spec:
  rules:
    - host: entrypoint.harmony.arkane-systems.lan
      http:
        paths:
          - path: /botkube
            pathType: Prefix
            backend:
              service:
                name: botkube
                port:
                  number: 3978
```

This appears to be functioning successfully for messaging traffic coming from Teams, per the commands functioning properly above.

**Expected behavior**

The notifications to be delivered as per documentation.

**Additional context**

Running BotKube v0.12.1 on Kubernetes 1.21.3 (k3s).
