### ISSUE TITLE
[BUG] helm `chart botkube/ingress.yaml` does not support `networking.k8s.io/v1` which is stable since kubernetes 1.19

### ISSUE THREAD

**Issue by RagingTonberry** [infracloudio/botkube#599]
**Describe the bug**
helm `chart botkube/ingress.yaml` does not support `networking.k8s.io/v1` which is stable since kubernetes 1.19.
As a result, on kubernetes 1.23 you cannot deploy the helm chart with the ingress, because you receive this error:
```
Release "botkube" does not exist. Installing it now.
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Ingress" in version "extensions/v1beta1"
```

The helm chart lists
```
[...]
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" }}
apiVersion: networking.k8s.io/v1beta1
{{ else }}
apiVersion: extensions/v1beta1
{{ end -}}
[...]
```
and should handle `networking.k8s.io/v1` now that it is the expected stable version.

**To Reproduce**
1. On a 1.23 cluster, use `helm` to install: `helm upgrade botkube infracloudio/botkube -i --namespace somenamespace --values kubebot.values.yaml` where `kubebot.values.yaml` contains appropriate config, specifically including `ingress.create` = `true`
```
communications:
  teams:
    enabled: true
    appID: blah
    appPassword: blah
    notiftype: short
    port: 3978
ingress:
  create: true
  host: avalidhost.com
  urlPath: teams/v1/messages/
  tls:
    enabled: true
    secretName: tls-secret
```

**Expected behavior**
An ingress should be created using API `networking.k8s.io/v1` with no error thrown.

**Screenshots**
n/a

**Additional context**
n/a
