### ISSUE TITLE
Change Slack unmarshalling error from error to warning level

### ISSUE THREAD

**Issue by bygui86** [infracloudio/botkube#619]
**Describe the bug**
I configured BotKube to send messages over Slack. BotKube app is installed in Slack workspace, I receive messages in different channels, everything work fine. But in the BotKube logs I see tons of "Slack unmarshalling error: RTM Error: Received unmapped event "user_status_changed"" messages like this

```
ERRO[2022-06-15T11:30:02Z] Slack unmarshalling error: RTM Error: Received unmapped event "user_status_changed": {"type":"user_status_changed","user":{"id":"***","team_id":"***","name":"jdoe","deleted":false,"color":"bc3663","real_name":"John Doe","tz":"Europe\/Amsterdam","tz_label":"Central European Summer Time","tz_offset":7200,"profile":{"title":"","phone":"","skype":"","real_name":"John Doe","real_name_normalized":"John Doe","display_name":"John","display_name_normalized":"John","fields":{},"status_text":"In a meeting","status_emoji":":spiral_calendar_pad:","status_emoji_display_info":[],"status_expiration":1655296200,"avatar_hash":"effbe98e0c63","image_original":"***original.jpg","is_custom_image":true,"email":"jdoe@domain.net","huddle_state":"default_unset","huddle_state_expiration_ts":0,"first_name":"John","last_name":"Doe","image_24":"***_24.jpg","image_32":"***_32.jpg","image_48":"***_48.jpg","image_72":"***_72.jpg","image_192":"***_192.jpg","image_512":"***_512.jpg","image_1024":"***_1024.jpg","status_text_canonical":"","team":"***"},"is_admin":false,"is_owner":false,"is_primary_owner":false,"is_restricted":false,"is_ultra_restricted":false,"is_bot":false,"is_app_user":false,"updated":1655292601,"is_email_confirmed":true,"who_can_share_contact_card":"EVERYONE","locale":"en-US"},"cache_ts":1655292601,"event_ts":"1655292602.019400"}
```

**BotKube configuration**
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: botkube
data:
  resource_config.yaml: |
    resources:
      - name: v1/nodes
        namespaces:
          include:
            - all
        events:
          - create
          - delete
          - update
      - name: v1/namespaces
        namespaces:
          include:
            - all
        events:
          - all
      # ... some others ...
    recommendations: false
    settings:
      configwatcher: false
      upgradeNotifier: true
      clustername: ceiba-test
      kubectl:
        enabled: false
        restrictAccess: true
        defaultNamespace: botkube
        commands:
          verbs:
            - "get"
            - "describe"
            - "logs"
          resources:
            - "namespaces"
            - "deployments"
            - "statefulsets"
            - "daemonsets"
            - "pods"
            - "services"
            - "cronjobs"
            - "jobs"
            - "configmaps"
            - "persistentvolumeclaims"
```

**To Reproduce**
1. Install BotKube app in Slack workspace
2. Configure BotKube with Slack values
3. Deploy BotKube in k8s in "botkube" namespace
4. Watching BotKube logs

**Expected behavior**
BotKube should ignore such messages without logging as error or directly not receiving such messages.

**Additional context**
K8s provider:   GCP/GKE
K8s version:   v1.21.11-gke.900
BotKube version:   v0.12.4
